# city_lookup.py

import pandas as pd
import reverse_geocoder as rg

def reverseGeocode(coordinates): 
    result = rg.search(coordinates)
    return (result)

def find_city(df):
    coordinates = list(zip(df['lat'],df['lon']))
    data = reverseGeocode(coordinates)
    df['mapped'] = [i['name'] for i in data]
    return df

# to create a lookup from reversed geo to custom locations 
# function will create a dictionary from two columns
def creat_dict(df, col1, col2):
    dictionary = df[[col1, col2]]
    dictionary = dictionary.replace({np.nan: 'none'})
    dictionary = dictionary.groupby('mapped')
    dictionary = dictionary[col1].apply(lambda s: s.tolist())
    dictionary = dictionary.to_dict()
    return dictionary
    
# city_lookup = creat_dict(df, 'city', 'mapped')

# df['city'] = df['mapped'].map(city_lookup)


city_lookup_dict = {'Alameda': 'alameda',
 'Albany': 'berkeley',
 'Alum Rock': 'san jose',
 'American Canyon': 'vallejo/richmond',
 'Antioch': 'hayward/dublin',
 'Aptos': 'santa cruz/gilroy',
 'Aptos Hills-Larkin Valley': 'santa cruz/gilroy',
 'Ashland': 'hayward/dublin',
 'Belmont': 'south bay',
 'Ben Lomond': 'santa cruz/gilroy',
 'Berkeley': 'berkeley',
 'Blackhawk': 'hayward/dublin',
 'Bodega Bay': 'north bay',
 'Bonny Doon': 'santa cruz/gilroy',
 'Boonville': 'north bay',
 'Boulder Creek': 'santa cruz/gilroy',
 'Brentwood': 'concord',
 'Brisbane': 'south san francisco',
 'Broadmoor': 'south san francisco',
 'Buena Vista': 'san jose',
 'Burbank': 'fremont/milpitas',
 'Burlingame': 'south san francisco',
 'Calistoga': 'vallejo/richmond',
 'Cambrian Park': 'south bay',
 'Campbell': 'san jose',
 'Caney': 'fremont/milpitas',
 'Capitola': 'santa cruz/gilroy',
 'Carmel Valley Village': 'santa cruz/gilroy',
 'Castro Valley': 'hayward/dublin',
 'Cherryland': 'hayward/dublin',
 'Clayton': 'concord',
 'Cloverdale': 'north bay',
 'Colma': 'south san francisco',
 'Concord': 'concord',
 'Cupertino': 'south bay',
 'Daly City': 'south san francisco',
 'Danville': 'hayward/dublin',
 'Davis': 'davis',
 'Diablo': 'hayward/dublin',
 'Dublin': 'hayward/dublin',
 'East Foothills': 'san jose',
 'East Palo Alto': 'south bay',
 'East Richmond Heights': 'vallejo/richmond',
 'El Cerrito': 'vallejo/richmond',
 'El Granada': 'santa cruz/gilroy',
 'El Sobrante': 'concord',
 'Eldridge': 'north bay',
 'Emeryville': 'berkeley',
 'Fairfax': 'marin/san rafael',
 'Fairfield': 'vallejo/richmond',
 'Fairview': 'hayward/dublin',
 'Foster City': 'south bay',
 'Fremont': 'fremont/milpitas',
 'Gilroy': 'santa cruz/gilroy',
 'Green Valley': 'vallejo/richmond',
 'Guerneville': 'north bay',
 'Hayward': 'hayward/dublin',
 'Healdsburg': 'north bay',
 'Hillsborough': 'south san francisco',
 'Hollister': 'santa cruz/gilroy',
 'Independence': 'fremont/milpitas',
 'Inverness': 'san francisco',
 "Ka'anapali": 'outside bay area',
 'Kensington': 'berkeley',
 'Lafayette': 'concord',
 'Lagunitas-Forest Knolls': 'marin/san rafael',
 'Larkfield-Wikiup': 'santa rosa',
 'Larkspur': 'san francisco',
 'Live Oak': 'santa cruz/gilroy',
 'Livermore': 'hayward/dublin',
 'Los Altos': 'south bay',
 'Los Altos Hills': 'south bay',
 'Los Gatos': 'south bay',
 'Lucas Valley-Marinwood': 'north bay',
 'Marin City': 'marin/san rafael',
 'Menlo Park': 'south san francisco',
 'Millbrae': 'south san francisco',
 'Milpitas': 'fremont/milpitas',
 'Montalvin': 'vallejo/richmond',
 'Moraga': 'concord',
 'Mountain House': 'hayward/dublin',
 'Mountain View': 'south bay',
 'Napa': 'vallejo/richmond',
 'Newark': 'fremont/milpitas',
 'North Fair Oaks': 'south bay',
 'North Richmond': 'vallejo/richmond',
 'Novato': 'north bay',
 'Oakland': 'oakland',
 'Oakley': 'concord',
 'Orinda': 'concord',
 'Pacheco': 'concord',
 'Pacifica': 'south san francisco',
 'Palo Alto': 'south bay',
 'Pasatiempo': 'santa cruz/gilroy',
 'Petaluma': 'north bay',
 'Piedmont': 'oakland',
 'Pinole': 'concord',
 'Pittsburg': 'concord',
 'Pleasant Hill': 'concord',
 'Pleasanton': 'hayward/dublin',
 'Redwood City': 'south bay',
 'Redwood Shores': 'south bay',
 'Richmond': 'vallejo/richmond',
 'Ridgemark': 'santa cruz/gilroy',
 'Rio Del Mar': 'santa cruz/gilroy',
 'Rodeo': 'vallejo/richmond',
 'Rohnert Park': 'santa rosa',
 'Rollingwood': 'vallejo/richmond',
 'Roseland': 'santa rosa',
 'Sacramento': 'sacramento',
 'Saint Helena': 'vallejo/richmond',
 'San Bruno': 'south san francisco',
 'San Carlos': 'south bay',
 'San Francisco': 'san francisco',
 'San Jose': 'san jose',
 'San Leandro': 'hayward/dublin',
 'San Lorenzo': 'hayward/dublin',
 'San Mateo': 'south san francisco',
 'San Rafael': 'marin/san rafael',
 'San Ramon': 'hayward/dublin',
 'Santa Clara': 'fremont/milpitas',
 'Santa Cruz': 'santa cruz/gilroy',
 'Santa Rosa': 'santa rosa',
 'Santa Venetia': 'marin/san rafael',
 'Saranap': 'concord',
 'Saratoga': 'south bay',
 'Sausalito': 'marin/san rafael',
 'Scotts Valley': 'santa cruz/gilroy',
 'Sebastopol': 'santa rosa',
 'Seven Trees': 'san jose',
 'Sonoma': 'north bay',
 'Soquel': 'santa cruz/gilroy',
 'South San Francisco': 'south san francisco',
 'Strawberry': 'marin/san rafael',
 'Suisun': 'vallejo/richmond',
 'Sunnyvale': 'south bay',
 'Takoradi': 'none',
 'Tamalpais-Homestead Valley': 'marin/san rafael',
 'Tara Hills': 'concord',
 'Tracy': 'tracy',
 'Twin Lakes': 'santa cruz/gilroy',
 'Ukiah': 'north bay',
 'Union City': 'fremont/milpitas',
 'Vacaville': 'vallejo/richmond',
 'Vallejo': 'vallejo/richmond',
 'Waldon': 'concord',
 'Walnut Creek': 'concord',
 'Watsonville': 'santa cruz/gilroy',
 'West Menlo Park': 'south bay',
 'West Sacramento': 'sacramento',
 'Windsor': 'north bay',
 'Woodside': 'south bay',
 'Yountville': 'vallejo/richmond'}